### ISSUE TITLE
Tab highlight is too dimmed

### ISSUE THREAD

**Issue by averrin** [paulpflug/opened-files#10]
Last version had too bright highlights, but now i almost cant see it
Maybe, make this value configurable?

**Comment by paulpflug** [comment]
:smile: 
I'm using the `@background-color-highlight` from the theme.
You can inspect the colors of your theme in the styleguide package `ctrl+shift+G`

You can play with it in your less file. Here are the selectors: 

``` less
// highlights the tabs
ul.tab-bar>li.tab.of-highlight,
ul.tab-bar>li.tab.of-highlight:before,
ul.tab-bar>li.tab.of-highlight:after {
  background-color: @background-color-highlight;
}
// highlights within opened files
.file-list .of-highlight:before {
  background-color: @background-color-highlight;
}
```

If you want, I can overwrite the color for a specific theme. Tell me which theme and which color works better..
