### ISSUE TITLE
Auto height

### ISSUE THREAD

**Issue by simurai** [paulpflug/opened-files#16]
Once https://github.com/atom/tree-view/pull/579 gets merged the `tree-view-resizer` will use flexbox. Then the inline `height` for the tree-view and opened-files isn't needed and could be replaced with something like:

``` less
.file-list.opened-files {
  flex: 1; // <- add
  overflow: auto; // <- add
}

.file-list.opened-files > ol.list-tree {
  // overflow: auto; // <- remove
}
```

Then it would share the space with the tree-view 50/50 and allow other packages to get added as well. Let me know if you run into any styling issues.
