### ISSUE TITLE
Double scrollbars

### ISSUE THREAD

**Issue by Instagit** [paulpflug/opened-files#27]
Atom version: 1.7.4
OS: Ubuntu 14.04

There are double scrollbars when the list elements are bigger than the wrapper.

This is because of

``` css
.file-list.opened-files {
    overflow: scroll;
}
```

![screen2](https://cloud.githubusercontent.com/assets/2681794/15820842/552b99ea-2bec-11e6-9c65-9cb3f8baecbe.png)

**Comment by Instagit** [comment]
I fixed this and https://github.com/paulpflug/opened-files/issues/28 by making the opened files area height completely adaptive and always show all open files:

``` css
.file-list.opened-files {
  height: auto;
  min-height: auto;
  max-height: none;
}

.file-list.opened-files > ol.list-tree .directory.list-nested-item .list-tree.entries {
  height: auto;
  max-height: none;
}
```

Might be a nice option to have regardless of what you choose to do about this issue.

**Comment by tautologistics** [comment]
Until this PR is accepted, I am using this in `~/.atom/style.less`:

``` css
// Fixes double vert scrollbar in opened-files view
.file-list.opened-files {
  overflow: auto;
}
.file-list.opened-files > ol.list-tree .directory.list-nested-item .list-tree.entries {
  overflow: visible;
}
```

**Comment by Beurt** [comment]
I added some CSS properties to @tautologistics proposal:

```css
// Fixes double vert scrollbar in opened-files view,
// allow to verticaly resize the opened-files panel
.file-list.opened-files {
  overflow: auto;
  resize: vertical;
  max-height: none;
}
.file-list.opened-files > ol.list-tree .directory.list-nested-item .list-tree.entries {
  overflow: visible;
}
```
And then it becomes possible to adjust height of the open-filed panel.
