### ISSUE TITLE
Feature request : show file name only

### ISSUE THREAD

**Issue by amebel** [paulpflug/opened-files#5]
It would be great to have a settings option to just show the filenames without the full path.

**Comment by paulpflug** [comment]
I think, I will enhance the list view and make it behave like in VS code.
So there will be filename first and then the path, but you can then hide the path with custom css.

Is that ok for you?

**Comment by amebel** [comment]
Yes, thanks :smile:

**Comment by paulpflug** [comment]
in version 0.2.0 you can disable paths by

``` less
.file-list.opened-files>ol.list-tree span.path {
  display:none;
}
```

I hope you like the changes ;)
