### ISSUE TITLE
Feature Request: Configure icon-pin placement

### ISSUE THREAD

**Issue by lexicalunit** [paulpflug/opened-files#6]
I think it looks a bit nicer to the left of the file name. Usually my tree-view isn't sized large enough to even see the pin icons if they're placed to the right of the file name, so I was mostly unable to take advantage of that feature during normal use.

![screen shot 2015-06-23 at 3 41 21 pm](https://cloud.githubusercontent.com/assets/1903876/8316993/096252fe-19c0-11e5-8d13-5bfdf9eddba7.png)

I tried to adjust things using just my personal `styles.less` file but was unable to make it work correctly. I tried using `float: left` but that caused a newline to be inserted between the icon and the name when the view was sized to be too small to fit the entire file name. Then I tried using `direction: rtl` but that caused overflow to scroll off the left edge, obscuring the pin icon.

Finally I resorted to modifying `file.vue` and when that didn't work, modifying the `file.js` variable `__vue_template__`. I assume there's some way to compile the `vue` file into a `js` file based on the naming of the directory, but it wasn't obvious to me what CLI tool I would use to do that.

Here's my fork: https://github.com/lexicalunit/opened-files/tree/lexicalunit_tweak. I didn't create a PR because I assume you'll want to implement this as a configuration setting.

I also used my `styles.less` file to:
- Remove the icon-x after file names.
- Adjust the margin between the directory names and icon-x.
- Disabled transition effects.
- Disabled box-shadow effects.
- Generally made the view look more like the tree-view in small ways.

I only mention this so it's more clear what you're seeing in my screenshot. Here's the `less` code:

``` less
.of-highlighted, ul.tab-bar > li.tab.of-highlighted {
    background-color: inherit;
    transition-property: none;
    transition-duration: 0;
}

.of-unhighlighted, ul.tab-bar > li.tab.of-unhighlighted {
    background-color: inherit;
    transition-property: none;
    transition-duration: 0;
}

.file-list.opened-files {
  box-shadow: none;
  border-bottom: 1px solid @syntax-wrap-guide-color;
  border-right: 1px solid @syntax-wrap-guide-color;
}

.file-list .list-item.file {
    .icon-x {
        display: none;
    }
}

.file-list .directory {
    .icon-x {
        margin-left: .5em;
    }
}
```
