### ISSUE TITLE
Light frame after recent update

### ISSUE THREAD

**Issue by averrin** [paulpflug/opened-files#9]
![opened_frame](https://cloud.githubusercontent.com/assets/426007/8352005/687c3c3e-1b3a-11e5-85ff-e526899f43e5.png)

It seems odd

**Comment by averrin** [comment]
Linux, kubuntu 15.04
atom: 0.211.0, theme: Accents

**Comment by paulpflug** [comment]
I have to admit, that is not very pretty..

I need a sort of seperation from the treeview. But I'm unsure what works best. Here is the current setting:

``` less
.file-list.opened-files {
  background-color: @tree-view-background-color;
  border-bottom: 1px solid @syntax-wrap-guide-color;
  border-right: 1px solid @syntax-wrap-guide-color;
}
```

you can overwrite it in your styles.less file. If you found something more pretty, let me know :smiley:
